<a href="https://colab.research.google.com/github/ganiyadav006/Customer_shopping_behavior/blob/main/costumer__shopping_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
df = pd.read_csv('messy_customer_shopping_behavior.csv')

In [6]:
df.head()
#first 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,409,34.0,NaN,Sneakers,Footwear,66,Alabama,L,White,Spring,3.4,Yes,Express,Yes,Yes,36,Cash,Fortnightly
1,3323,52.0,FEMALE,Sweater,Clothing,92,Indiana,XL,Orange,Winter,4.6,No,Next Day Air,No,No,43,PayPal,Weekly
2,683,23.0,Male,Jacket,Outerwear,29,Missouri,M,Brown,Summer,4.0,Yes,Standard,Yes,Yes,49,Credit Card,Bi-Weekly
3,3159,30.0,Female,Jewelry,Accessories,77,Mississippi,M,Gray,Winter,4.9,No,2-Day Shipping,No,No,44,Credit Card,Monthly
4,2357,57.0,Male,Backpack,Accessories,58,Montana,M,Gray,Summer,3.0,No,Free Shipping,No,No,27,Debit Card,Quarterly

In [7]:
#dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3980 entries, 0 to 3979
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3980 non-null   int64
 1   Age                     3862 non-null   float64
 2   Gender                  3865 non-null   object
 3   Item Purchased          3980 non-null   object
 4   Category                3980 non-null   object
 5   Purchase Amount (USD)   3980 non-null   object
 6   Location                3861 non-null   object
 7   Size                    3980 non-null   object
 8   Color                   3859 non-null   object
 9   Season                  3980 non-null   object
 10  Review Rating           3940 non-null   object
 11  Subscription Status     3980 non-null   object
 12  Shipping Type           3980 non-null   object
 13  Discount Applied        3980 non-null   object
 14  Promo Code Used         3980 non-null   object
 15  Previous Purchases      3980 non-null   object
 16  Payment Method          3860 non-null   object
 17  Frequency of Purchases  3980 non-null   object
dtypes: float64(1), int64(1), object(16)
memory usage: 559.8+ KB

In [9]:
df.shape
#tells how many rows and columns

(3980, 18)

In [10]:
df.isnull().sum()
#shows missing values

Customer ID                 0
Age                       118
Gender                    115
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                  119
Size                        0
Color                     121
Season                      0
Review Rating              40
Subscription Status         0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Payment Method            120
Frequency of Purchases      0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(49)

In [12]:
df = df.drop_duplicates()

In [13]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [14]:
df = df.apply(lambda x : x.str.strip() if x.dtype == "object" else x)
#removes extra spaces

In [17]:
#Standardize text cases
#gender column
df["Gender"] = df["Gender"].str.lower()
#Season column
df["Season"] = df["Season"].str.capitalize()

In [21]:
#Handle currency symbols
#converts to numbers
df["Purchase Amount (USD)"] = (df["Purchase Amount (USD)"].astype(str).str.replace("$","",regex =False) )
df["Purchase Amout (USD)"] = pd.to_numeric( df["Purchase Amount (USD)"], errors = "coerce" )

In [22]:
#Clean REview ratings
#remove text
df["Review Rating"] = (df["Review Rating"].astype(str).str.replace(" stars","",regex=False))
df["Review Rating"] = pd.to_numeric(df["Review Rating"],errors ="coerce")

In [24]:
#Handle Invalid Age values
#checks invalid ages
df[df["Age"]<0]
#replace with NaN
df.loc[df["Age"]<0,"Age"] =np.nan

In [25]:
#Fix MIxed Data Types
df["Previous Purchases"] = pd.to_numeric(df["Previous Purchases"],errors ="coerce")

In [28]:
#Fill missing values
#numeric columns
numeric_cols =df.select_dtypes(include=np.number).columns
for col in numeric_cols:
  df[col] = df[col].fillna(df[col].median())
#categorical columns
cat_cols = df.select_dtypes(include ="object").columns
for col in cat_cols:
  df[col] = df[col].fillna(df[col].mode()[0])

In [29]:
df.dtypes
#check data types

Customer ID                 int64
Age                       float64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)      object
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating              object
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases        float64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [30]:
df.describe()
#Detect Outliers aggregate fun

       Customer ID          Age  Previous Purchases
count  3980.000000  3980.000000         3980.000000
mean   1949.334171    44.007789           25.406784
std    1125.096180    14.930574           14.365481
min       1.000000    18.000000            1.000000
25%     975.750000    31.000000           13.000000
50%    1946.500000    44.000000           25.000000
75%    2923.250000    57.000000           38.000000
max    3900.000000    70.000000           50.000000

In [34]:
df.columns = df.columns.str.lower().str.replace(" ","_")

In [35]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3980 entries, 0 to 3979
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3980 non-null   int64
 1   age                     3980 non-null   float64
 2   gender                  3980 non-null   object
 3   item_purchased          3980 non-null   object
 4   category                3980 non-null   object
 5   purchase_amount_(usd)   3980 non-null   object
 6   location                3980 non-null   object
 7   size                    3980 non-null   object
 8   color                   3980 non-null   object
 9   season                  3980 non-null   object
 10  review_rating           3980 non-null   object
 11  subscription_status     3980 non-null   object
 12  shipping_type           3980 non-null   object
 13  discount_applied        3980 non-null   object
 14  promo_code_used         3980 non-null   object
 15  previous_purchases      3980 non-null   float64
 16  payment_method          3980 non-null   object
 17  frequency_of_purchases  3980 non-null   object
dtypes: float64(2), int64(1), object(15)
memory usage: 559.8+ KB

       customer_id          age  previous_purchases
count  3980.000000  3980.000000         3980.000000
mean   1949.334171    44.007789           25.406784
std    1125.096180    14.930574           14.365481
min       1.000000    18.000000            1.000000
25%     975.750000    31.000000           13.000000
50%    1946.500000    44.000000           25.000000
75%    2923.250000    57.000000           38.000000
max    3900.000000    70.000000           50.000000

In [36]:
df.to_csv("cleaned_customer_shopping_behavior.csv",index=False)